### ISSUE TITLE
issue in executing the script

### ISSUE THREAD

**Issue by Marwen-Brini** [iMartinezMateu/unitywebpackager#1]
hello i'm having trouble executing your project i keep getting errors such as 
"Traceback (most recent call last):
  File "C:\MSI\project\unitywebpackager-master\unitywebpackager.py", line 26, in <module>
    import unitywebpackager_ops
  File "C:\MSI\project\unitywebpackager-master\unitywebpackager_ops.py", line 27, in <module>
    import progressbar
ModuleNotFoundError: No module named 'progressbar'"
would appreciate any help on the matter and thank you.

**Comment by iMartinezMateu** [comment]
Hello,

You do not have the progressbar library installed in your machine. Install it via pip and then, try again.

**Comment by Marwen-Brini** [comment]
it's solved i obtained the binaries files, really awesome work bro thank you :)
